User.class: User.java Pig.class Pet.class Attribute.class Hunger.class Energy.class Hygiene.class Happiness.class
	javac User.java

Pig.class: Pig.java
	javac Pig.java

Pet.class: Pet.java
	javac Pet.java

Attribute.class: Attribute.java
	javac Attribute.java

Hunger.class: Hunger.java
	javac Hunger.java

Energy.class: Energy.java
	javac Energy.java

Hygiene.class: Hygiene.java
	javac Hygiene.java

Happiness.class: Happiness.java
	javac Happiness.java

run: User.class
	java User

clean:
	rm *.class